#!/usr/bin/env node
/* Packs ../art into a single Phaser texture atlas.

   The canvas build forges every sprite at load time and blits them one at a
   time. That is the thing the move to Phaser is meant to stop: a GPU renderer
   batches draws that share a texture, and shares a texture only if the frames
   live in one image. So the atlas is not a nicety here, it is the entire
   point -- 239 separate textures would batch no better than the canvas build
   already does.

   art/ is generated by ../tools/export-art.js from the forge code in
   index.html, so this reads generated input and writes generated output:
   nothing in public/ should ever be hand-edited.

   Pure JS on purpose (pngjs, no native build), because this has to run under
   Termux on the phone as well as on a desktop.

   Run: node tools/pack-atlas.js
*/
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const ART  = path.join(here, '..', '..', 'art');
const OUT  = path.join(here, '..', 'public');

const PAD = 2;              // bleed guard: stops a neighbour's edge sampling in

function readAll(dir, prefix, into) {
  if (!fs.existsSync(dir)) return;
  for (const f of fs.readdirSync(dir).sort()) {
    if (!f.endsWith('.png')) continue;
    const png = PNG.sync.read(fs.readFileSync(path.join(dir, f)));
    into.push({ name: prefix + path.basename(f, '.png'),
                w: png.width, h: png.height, png });
  }
}

// Shelf packing, tallest first. A max-rects packer would waste less, and at
// this sprite count the difference is a few hundred kilobytes of texture
// against a great deal more code to get wrong.
function pack(frames, maxW) {
  frames.sort((a, b) => b.h - a.h || b.w - a.w);
  let x = PAD, y = PAD, shelf = 0, W = 0;
  for (const f of frames) {
    if (x + f.w + PAD > maxW) { x = PAD; y += shelf + PAD; shelf = 0; }
    f.x = x; f.y = y;
    x += f.w + PAD;
    shelf = Math.max(shelf, f.h);
    W = Math.max(W, f.x + f.w + PAD);
  }
  return { w: maxW, h: y + shelf + PAD };
}

const frames = [];
// Folder name becomes the frame prefix, so "bestiary/thrall-run-0" is unique
// against "heroes/isaac-run-0" without any renaming.
for (const d of ['heroes', 'bestiary', 'props', 'chests', 'misc', 'walls'])
  readAll(path.join(ART, d), d + '/', frames);
// cycles/ is contact strips for looking at, not for drawing. Excluding it
// keeps a megabyte of duplicated pixels out of GPU memory.

if (!frames.length) {
  console.error('no PNGs under ' + ART + ' — run `node tools/export-art.js` in the repo root first');
  process.exit(1);
}

// Widest sprite decides the floor; 2048 is the safe universal GL texture size.
const widest = Math.max(...frames.map(f => f.w)) + PAD * 2;
const size = pack(frames, Math.max(2048, 1 << Math.ceil(Math.log2(widest))));
if (size.h > 4096) {
  console.error('atlas is ' + size.w + 'x' + size.h + ' — over the 4096 a lot of ' +
                'mobile GL drivers still cap at. Split it before shipping.');
  process.exit(1);
}

const sheet = new PNG({ width: size.w, height: size.h });
sheet.data.fill(0);
for (const f of frames) {
  // bitblt copies straight into the sheet; premultiplied alpha is Phaser's job
  PNG.bitblt(f.png, sheet, 0, 0, f.w, f.h, f.x, f.y);
}

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'atlas.png'), PNG.sync.write(sheet));

// TexturePacker's JSON Hash, which Phaser reads without a custom parser.
const json = { frames: {}, meta: {
  app: 'tools/pack-atlas.js', version: '1',
  image: 'atlas.png', format: 'RGBA8888',
  size: { w: size.w, h: size.h }, scale: '1'
} };
for (const f of frames) {
  json.frames[f.name] = {
    frame: { x: f.x, y: f.y, w: f.w, h: f.h },
    rotated: false, trimmed: false,
    spriteSourceSize: { x: 0, y: 0, w: f.w, h: f.h },
    sourceSize: { w: f.w, h: f.h }
  };
}
fs.writeFileSync(path.join(OUT, 'atlas.json'), JSON.stringify(json) + '\n');

// The stat block travels with the art, so the game does not need a second
// source of truth for what a thrall is.
const man = path.join(ART, 'manifest.json');
if (fs.existsSync(man)) fs.copyFileSync(man, path.join(OUT, 'manifest.json'));

const kb = n => (n / 1024).toFixed(0) + 'kB';
console.log('atlas ' + size.w + 'x' + size.h + '  ' + frames.length + ' frames  ' +
            kb(fs.statSync(path.join(OUT, 'atlas.png')).size));
