#!/data/data/com.termux/files/usr/bin/bash
# Sets up this workspace on a phone under Termux. Safe to re-run.
#
# Everything here is pure JS or a prebuilt binary -- Phaser has one dependency
# and it is not native, pngjs is JS, and esbuild ships an android-arm64 build --
# so nothing has to compile on the device.
set -eu

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }

say "1/4  packages"
# nodejs-lts is the steadier of the two in Termux; either works.
pkg install -y nodejs-lts git || pkg install -y nodejs git

say "2/4  versions"
node --version
npm --version

cd "$(dirname "$0")/.."

say "3/4  dependencies"
# --no-audit/--no-fund keep it quiet on a slow connection; no native builds.
npm install --no-audit --no-fund

say "4/4  first build"
# The atlas needs ../art, which is generated by tools/export-art.js in the repo
# root and IS committed -- so a fresh clone can pack without running Chromium,
# which Termux cannot do.
if [ -d ../art ] && [ -n "$(ls -A ../art/bestiary 2>/dev/null)" ]; then
  npm run atlas
else
  echo "  ../art is empty. It is committed, so this usually means a partial"
  echo "  clone. Without it there is nothing to pack and the game has no art."
fi
npm run build

cat <<'DONE'

Ready.

  npm run dev      build on save, and serve on http://localhost:8080
  npm run serve    serve only
  npm run build    one-off bundle
  npm run atlas    repack public/atlas.png from ../art

Then open http://localhost:8080 in the phone's browser.

Serve rather than opening the file directly: a WebGL context over file:// is
refused on some Android WebView builds, and that failure looks like the game
booting to a black screen rather than like an error.

Two things that do NOT work on the device, by design:
  - tools/export-art.js needs Chromium to re-forge the sprites. art/ is
    committed so you never need it on the phone; run it on a desktop after
    changing a forge function in ../index.html.
  - The Playwright suites are desktop-only for the same reason.
DONE
