#!/usr/bin/env node
/* What art this game needs, written down.
 *
 * GENERATED from art/ and art/manifest.json, deliberately, because a
 * hand-written spec drifts from the code the first time a frame is added and
 * then quietly misleads whoever is drawing to it. Every size here is measured
 * from the file the game actually loads.
 *
 * This is the document you hand to an artist, or check an asset pack against.
 * Anything drawn to it can be dropped into art-custom/ one frame at a time --
 * see phaser/tools/pack-atlas.js -- so the delve never has to wait for all 244.
 *
 * Run: node tools/art-spec.js   ->  art/SPEC.md
 *
 * No dependencies: a PNG's width and height are in its IHDR at a fixed offset,
 * and reading twelve bytes beats making a root-level tool -- which has no
 * node_modules of its own and has to run under Termux -- depend on the Phaser
 * build's.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const ART = path.join(here, '..', 'art');
const man = JSON.parse(fs.readFileSync(path.join(ART, 'manifest.json'), 'utf8'));
const SS = man.supersample || 2;

/* PNG signature (8) + chunk length (4) + 'IHDR' (4), then width and height as
 * big-endian 32-bit. Checked rather than assumed: a file that is not a PNG
 * would otherwise be reported with garbage dimensions. */
function size(file) {
  const b = fs.readFileSync(file);
  if (b.length < 24 || b.readUInt32BE(0) !== 0x89504e47 || b.toString('latin1', 12, 16) !== 'IHDR') {
    throw new Error(file + ' is not a PNG');
  }
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

const read = d => {
  const dir = path.join(ART, d);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter(f => f.endsWith('.png')).sort().map(f => {
    const { w, h } = size(path.join(dir, f));
    return { name: path.basename(f, '.png'), w, h };
  });
};

// Group frames that differ only by a trailing -N, so a walk cycle is one row
// rather than eight.
function group(list) {
  const out = new Map();
  for (const f of list) {
    const m = f.name.match(/^(.*?)-(\d+)$/);
    const key = m ? m[1] + '-N' : f.name;
    if (!out.has(key)) out.set(key, { key, n: 0, w: f.w, h: f.h, sizes: new Set() });
    const g = out.get(key);
    g.n++; g.sizes.add(f.w + 'x' + f.h);
  }
  return [...out.values()];
}

const L = [];
L.push('# The Rivenmark — art specification');
L.push('');
L.push('GENERATED by `tools/art-spec.js`. Do not hand-edit: it is measured from');
L.push('the files the game loads, so it cannot drift from them.');
L.push('');
L.push('## The contract');
L.push('');
L.push('- **Supersample ' + SS + '.** Everything in `art/` is drawn at ' + SS +
       '× and rendered at 1/' + SS + '. A 88×88 file is 44×44 world units.');
L.push('- **Authored art may be any resolution.** Drop a replacement into');
L.push('  `art-custom/<folder>/<same-name>.png` at any size; the packer records');
L.push('  its ratio to the frame it replaces and the game divides by it. A 4×');
L.push('  thrall occupies exactly the world space the 2× one did.');
L.push('- **Keep the aspect ratio.** The packer warns about any replacement that');
L.push('  changes shape: the game positions by centre and sorts by foot, so a');
L.push('  different shape does not sit where the old one sat.');
L.push('- **Transparent PNG, straight alpha.** Premultiplication is the renderer\'s job.');
L.push('- **One frame at a time is fine.** Nothing needs replacing all at once.');
L.push('');
L.push('## Anchoring');
L.push('');
L.push('Bodies and heroes are drawn centred on their world position, and sorted');
L.push('against each other by that position — so the FEET should sit at the');
L.push('centre of the canvas, not the middle of the torso, or a body will stand');
L.push('in front of something it is behind. Standing scenery (pillars, barrels,');
L.push('tombs) follows the same rule: the base at the centre, the shaft running up.');
L.push('');
L.push('## What is needed');
L.push('');

const FOLDERS = [
  ['heroes', 'The two Vanguards. `-rest`, an 8-frame `-run-N` and an 8-frame `-walk-N` each.'],
  ['bestiary', 'Everything that fights you. `-rest` plus an 8-frame `-run-N` per kind.'],
  ['props', 'Scenery. `-N` variants are rolled per placement, so they should differ visibly.'],
  ['walls', 'The masonry. `top-N` is the lit face of a solid cell; `course-V-Q` is the band along an exposed face, V a variant and Q a quarter-turn.'],
  ['chests', 'Coffers, shut and open.'],
  ['misc', 'The shadow every standing thing casts, and slag on the floor.']
];

let total = 0;
for (const [d, blurb] of FOLDERS) {
  const list = read(d);
  if (!list.length) continue;
  total += list.length;
  L.push('### `' + d + '/` — ' + list.length + ' frames');
  L.push('');
  L.push(blurb);
  L.push('');
  L.push('| frame | count | size (' + SS + '×) | world |');
  L.push('|---|---|---|---|');
  for (const g of group(list).sort((a, b) => a.key.localeCompare(b.key))) {
    // Every size, not a count of them. A group with two is usually a set of
    // quarter-turns -- 100x30 along an x face and 30x100 along a y one -- and
    // "2 sizes" is exactly the thing someone drawing them needs told.
    const sizes = [...g.sizes].sort();
    const world = sizes.map(z => {
      const [w, h] = z.split('x').map(Number);
      return Math.round(w / SS) + '×' + Math.round(h / SS);
    });
    L.push('| `' + d + '/' + g.key + '` | ' + g.n + ' | ' + sizes.join(', ') +
           ' | ' + world.join(', ') + ' |');
  }
  L.push('');
}

L.push('## The bestiary, in detail');
L.push('');
L.push('Every kind, with what it does — so the art can say what the thing is');
L.push('before the player has been hit by it. `radius` is the body\'s collision');
L.push('size in world units, which the silhouette should roughly fill.');
L.push('');
L.push('| kind | radius | life | damage | role | colour | first seen |');
L.push('|---|---|---|---|---|---|---|');
for (const [k, v] of Object.entries(man.kinds || {})) {
  L.push('| `' + k + '` | ' + v.radius + ' | ' + v.life + ' | ' + v.damage + ' | ' +
         (v.role || '—') + ' | `' + (v.colour || '—') + '` | delve ' +
         (v.introduced_at_depth ?? '—') + ' |');
}
L.push('');
L.push('## Animation');
L.push('');
L.push('`gait_poses` is ' + (man.gait_poses || 8) + '. Cycles advance by DISTANCE');
L.push('TRAVELLED, not on a clock: a body slowed to half speed takes half-length');
L.push('steps rather than moonwalking. Draw the run as a loop that reads at any');
L.push('playback rate, because there is no fixed one.');
L.push('');
L.push('Contact sheets of every existing cycle are in `art/cycles/` — one strip');
L.push('per kind, for looking at rather than loading.');
L.push('');
L.push('---');
L.push('');
L.push(total + ' frames total, from ' + (man.generated_from || 'the forge') + '.');

fs.writeFileSync(path.join(ART, 'SPEC.md'), L.join('\n') + '\n');
console.log('art/SPEC.md written — ' + total + ' frames across ' + FOLDERS.length + ' folders');
